### ISSUE TITLE
example?

### ISSUE THREAD

**Issue by ralyodio** [Loknar/node-mouse-cursors#1]
does this example no longer work?

https://node-mouse-cursors.herokuapp.com/

**Comment by Loknar** [comment]
Well, it works for me at least, you need to open it in two windows (or two different persons open it on different computers), it becomes rather sluggish looking when more than two people are jerking their mouses around though, that has to do with the fact that we're sending new mouse location every time a mouse move event in our browser is triggered (hence, we spam the kazdingo out of the service), we might probably be able to make it look/function better by faking some of the movement and only send movement when it's over some threshold of movement length or a given amount of time has passed since we last sent updated location.

![NPM](http://i.imgur.com/vKfdKBB.gif)

Also maybe use more than one socket? I admit I haven't played around much with socket.io since I experienced with this example.

If this answers your question please close this issue. :wink:

**Comment by ralyodio** [comment]
yup, that works. it just looked like an error page
